DefaultExperiment: &defaults
    dataset_folder: '/home/guests/manal_hamdi/manal/TGRAFT/datasets/ACDC_processed/'
    wandb_entity: khammernik
    experiment_dir: './experiments/'
    gpus: 0
    num_workers: 4
    name: default
    small: False
    stage: acdc
    validation: acdc
    batch_size: 1
    lr: 0.0004 
    wdecay: 0.0001 
    max_seq_len: 19
    iters: 12
    epsilon: 1e-8
    clip: 1.0
    dropout: 0.0
    gamma: 0.8
    add_noise: False
    beta_photo: {}
    beta_spatial: {}
    beta_temporal: {}
    num_steps: {}
    model: {}
    restore_ckpt: {}
    add_normalisation: {}
    
GroupwiseFull:
    <<: *defaults
    beta_photo: {1}
    beta_spatial: {10.0}
    beta_temporal: {10.0}
    num_steps: {400}
    
PairwiseFull:
    <<: *defaults
    beta_photo: {1}
    beta_spatial: {10.0}
    beta_temporal: {0.0}
    num_steps: {400}
    add_normalisation: False