DefaultExperiment: &defaults
    dataset_folder: '/home/peter_studt/Manal/TGRAFT/datasets/ACDC_processed/'
    gpus: [0]
    num_workers: 4
    small: False
    stage: 'acdc'
    validation: ['acdc']
    batch_size: 1
    lr: 0.0004 
    wdecay: 0.0001 
    max_seq_len: 4
    iters: 12
    epsilon: 0.00000001
    clip: 1.0
    dropout: 0.0
    gamma: 0.8
    add_noise: False
    mixed_precision: False
    restore_ckpt: null
    alternate_corr: False
    
GroupwiseFull:
    <<: *defaults
    name: 'GroupwiseFull'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    num_steps: 400
    add_normalisation: False
PairwiseFull:
    <<: *defaults
    name: 'PairwiseFull'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 0.0
    num_steps: 2
    add_normalisation: False