DefaultExperiment: &defaults
    dataset_folder: 'datasets/ACDC_processed/'
    gpus: [0]
    num_workers: 4
    small: False
    dataset: acdc
    stage: 'acdc'
    validation: ['acdc']
    batch_size: 1
    lr: 0.0004 
    wdecay: 0.0001 
    max_seq_len: 19
    iters: 12
    epsilon: 0.00000001
    clip: 1.0
    dropout: 0.0
    gamma: 0.8
    add_noise: False
    mixed_precision: False
    restore_ckpt: null
    alternate_corr: False
    composed_flows: False
    beta_comp: 1.0
    learn_temp: False
    comp_photo: False
    comp_temp: False
    comp_spa: False

GroupwiseFull:
    <<: *defaults
    name: 'GroupwiseFull'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    num_steps: 400
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
#---------------------
GroupwiseFull_LearnTemp_100spa_setting3_18:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_setting3_18'
    max_seq_len: 18
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
GroupwiseFull_LearnTemp_100spa_setting3_17:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_setting3_17'
    max_seq_len: 17
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
GroupwiseFull_LearnTemp_default:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_default'
    max_seq_len: 10
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_default_15:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_default_15'
    max_seq_len: 15
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_LearnTemp_default_17:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_default_17'
    max_seq_len: 17
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_setting2_10:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_setting2_10'
    max_seq_len: 10
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_LearnTemp_setting3_15:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_setting3_15'
    max_seq_len: 15
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_LearnTemp_avgFalse:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_avgFalse'
    max_seq_len: 15
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_default_18:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_default_18'
    max_seq_len: 18
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_LearnTemp_100spa_avgFalse:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_avgFalse'
    max_seq_len: 19
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_100spa:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa'
    max_seq_len: 19
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_LearnTemp_100spa_mean_default:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_mean_default'
    max_seq_len: 19
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_100spa_mean_setting2:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_mean_setting2'
    max_seq_len: 19
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_100spa_mean_setting2_15:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_mean_setting2_15'
    max_seq_len: 15
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True

GroupwiseFull_LearnTemp_100spa_mean_setting3:
    <<: *defaults
    name: 'GroupwiseFull_LearnTemp_100spa_mean_setting3'
    max_seq_len: 19
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
    
GroupwiseFull_photoCFB_19:
    <<: *defaults
    name: 'GroupwiseFull_photoCFB_19'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    max_seq_len: 19
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    comp_photo: True
GroupwiseFull_photoCFB_18:
    <<: *defaults
    name: 'GroupwiseFull_photoCFB_18'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    max_seq_len: 18
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    comp_photo: True
    
GroupwiseFull_photoCFB_spaCFB_tempCFB_18:
    <<: *defaults
    name: 'GroupwiseFull_photoCFB_spaCFB_tempCFB_18'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    max_seq_len: 18
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    comp_photo: True
    comp_temp: True
    comp_spa: True
#--------------------
    
GroupwiseFull_fwdbwdcomp_photo_spa_temp:
    <<: *defaults
    name: 'pop'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    
GroupwiseFull_fwdbwdcomp_photo_100spa_temp:
    <<: *defaults
    name: 'bluby'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
#------------------- Increasing weight of spa ------------------------
GroupwiseFull_LearnFlow_100spa_len4:
    <<: *defaults
    name: '4learn_param18'
    max_seq_len: 4
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: False
    learn_temp: True
GroupwiseFull_100comp_1000spa:
    <<: *defaults
    name: 'GroupwiseFull_100comp_1000spa'
    beta_photo: 1
    beta_spatial: 1000.0
    beta_temporal: 10.0
    beta_comp: 100.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    
GroupwiseFull_allcomp:
    <<: *defaults
    name: 'GroupwiseFull_allcomp'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True

    
GroupwiseFull_photocomp:
    <<: *defaults
    name: 'GroupwiseFull_photocomp31'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    beta_comp: 1.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True

GroupwiseFull_100spa:
    <<: *defaults
    name: 'GroupwiseFull_100spa'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 400
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'

GroupwiseFull_50spa:
    <<: *defaults
    name: 'GroupwiseFull_50spa'
    beta_photo: 1
    beta_spatial: 50.0
    beta_temporal: 10.0
    num_steps: 400
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'

GroupwiseFull_20spa:
    <<: *defaults
    name: 'GroupwiseFull_20spa'
    beta_photo: 1
    beta_spatial: 20.0
    beta_temporal: 10.0
    num_steps: 400
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'

GroupwiseFull_compFlow:
    <<: *defaults
    name: 'GroupwiseFull_compFlow'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    
GroupwiseFull_compFlow_100spa:
    <<: *defaults
    name: 'GroupwiseFull_compFlow_100spa22'
    beta_photo: 1
    beta_spatial: 100.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True

GroupwiseFull_compFlow_1000spa:
    <<: *defaults
    name: 'GroupwiseFull_compFlow_1000spa'
    beta_photo: 1
    beta_spatial: 1000.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    composed_flows: True
    
#------------------- END ------------------------
GroupwiseFull200:
    <<: *defaults
    name: 'GroupwiseFull200_232'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    
GroupwiseFull_PCA_200:
    <<: *defaults
    name: 'GroupwiseFull_PCA_200'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'

GroupwisePhoto:
    <<: *defaults
    name: 'GroupwisePhoto'
    beta_photo: 1
    beta_spatial: 0.0
    beta_temporal: 0.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    
GroupwisePhotoSpa:
    <<: *defaults
    name: 'GroupwisePhotoSpa'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 0.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    
GroupwisePhotoTemp:
    <<: *defaults
    name: 'GroupwisePhotoTemp'
    beta_photo: 1
    beta_spatial: 0.0
    beta_temporal: 10.0
    num_steps: 200
    add_normalisation: False
    model: 'group'
    train_or_test: 'train'
    
PairwiseFull:
    <<: *defaults
    name: 'PairwiseFull'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 0.0
    num_steps: 400
    add_normalisation: False
    model: 'pair'
    train_or_test: 'train'

PairwiseFull200:
    <<: *defaults
    name: 'PairwiseFull200'
    beta_photo: 1
    beta_spatial: 10.0
    beta_temporal: 0.0
    num_steps: 200
    add_normalisation: False
    model: 'pair'
    train_or_test: 'train'

Eval: &eval_defaults
    dataset: acdc
    dataset_folder: "/home/guests/manal_hamdi/manal/TGRAFT/datasets/ACDC_processed/"
    small: False
    mixed_precision: False
    alternate_corr: False
    gpus: [0]
    gamma: 0.8
    batch_size: 1
    output_file: "debugging_exp_eval_results.txt"
    train_or_test: 'test'
    dropout: 0.0
    iters: 2

Eval_peter:
    <<: *eval_defaults
    dataset_folder: "/home/peter_studt/Manal/TGRAFT/datasets/ACDC_processed/"
    name: "PairwiseFull"
    restore_ckpt: "mymodels/PairwiseFull/PairwiseFull_1.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 15
    
Eval_8_PairwiseFull:
    <<: *eval_defaults
    name: "Pair_Avg_19_noNorm_full_398"
    restore_ckpt: "october_checkpoints/raft_pairwise/raft_pairwise_398.pth"
    add_normalisation: False
    model: 'pair'
    max_seq_len: 8

Eval_8_GroupwiseFull:
    <<: *eval_defaults
    name: "2_Avg_19_noNorm_full_398"
    restore_ckpt: "october_checkpoints/2_Avg_19_noNorm_full/2_Avg_19_noNorm_full_398.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8

Eval_8_GroupwiseNorm298:
    <<: *eval_defaults
    name: "Avg_Norm_full"
    restore_ckpt: "october_checkpoints/Avg_Norm_full/Avg_Norm_full_298.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8

Eval_19_PairwiseFull:
    <<: *eval_defaults
    name: "2_Avg_19_noNorm_full_398"
    restore_ckpt: "october_checkpoints/2_Avg_19_noNorm_full/2_Avg_19_noNorm_full_398.pth"
    add_normalisation: False
    model: 'pair'
    max_seq_len: 19

Eval_19_GroupwiseFull_398:
    <<: *eval_defaults
    name: "2_Avg_19_noNorm_full_398"
    restore_ckpt: "october_checkpoints/2_Avg_19_noNorm_full/2_Avg_19_noNorm_full_398.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_19_Groupwise_photo:
    <<: *eval_defaults
    name: "Avg_19_noNorm_photo"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo/Avg_19_noNorm_photo_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_19_Groupwise_photo_spa:
    <<: *eval_defaults
    name: "Avg_19_noNorm_photo_10spa"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo_10spa/Avg_19_noNorm_photo_10spa_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_19_Groupwise_photo_temp:
    <<: *eval_defaults
    name: "Avg_19_noNorm_photo_10temp"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo_10temp/Avg_19_noNorm_photo_10temp_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19
    
Eval_19_GroupwiseFull_198:
    <<: *eval_defaults
    name: "Avg_19_noNorm_full"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_full/Avg_19_noNorm_full_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19


#*******************************

Eval_12_GroupwiseFull_398:
    <<: *eval_defaults
    name: "2_Avg_12_noNorm_full_398"
    restore_ckpt: "october_checkpoints/2_Avg_19_noNorm_full/2_Avg_19_noNorm_full_398.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 12

Eval_12_Groupwise_photo:
    <<: *eval_defaults
    name: "Avg_12_noNorm_photo"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo/Avg_19_noNorm_photo_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 12

Eval_12_Groupwise_photo_spa:
    <<: *eval_defaults
    name: "Avg_12_noNorm_photo_10spa"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo_10spa/Avg_19_noNorm_photo_10spa_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 12

Eval_12_Groupwise_photo_temp:
    <<: *eval_defaults
    name: "Avg_12_noNorm_photo_10temp"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_photo_10temp/Avg_19_noNorm_photo_10temp_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 12
    
Eval_12_GroupwiseFull_198:
    <<: *eval_defaults
    name: "Avg_12_noNorm_full"
    restore_ckpt: "october_checkpoints/Avg_19_noNorm_full/Avg_19_noNorm_full_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 12
    
    
#******************************* EVALUATING NEW IMPLEMENTATION ****************************
#******** 19 ****************************
Eval_config_19_GroupwiseFull_398:
    <<: *eval_defaults
    name: "GroupwiseFull"
    restore_ckpt: "october_checkpoints/GroupwiseFull/GroupwiseFull_398.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_config_19_GroupwisePhoto:
    <<: *eval_defaults
    name: "GroupwisePhoto"
    restore_ckpt: "october_checkpoints/GroupwisePhoto/GroupwisePhoto_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_config_19_GroupwisePhotoSpa:
    <<: *eval_defaults
    name: "GroupwisePhotoSpa"
    restore_ckpt: "october_checkpoints/GroupwisePhotoSpa/GroupwisePhotoSpa_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_config_19_GroupwisePhotoTemp:
    <<: *eval_defaults
    name: "GroupwisePhotoTemp"
    restore_ckpt: "october_checkpoints/GroupwisePhotoTemp/GroupwisePhotoTemp_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19
    
Eval_config_19_GroupwiseFull_198:
    <<: *eval_defaults
    name: "GroupwiseFull200"
    restore_ckpt: "october_checkpoints/GroupwiseFull200/GroupwiseFull200_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 19

Eval_config_19_PairwiseFull:
    <<: *eval_defaults
    name: "PairwiseFull"
    restore_ckpt: "october_checkpoints/PairwiseFull/PairwiseFull_398.pth"
    add_normalisation: False
    model: 'pair'
    max_seq_len: 19
#******** 8 ****************************
Eval_config_8_GroupwiseFull_398:
    <<: *eval_defaults
    name: "GroupwiseFull"
    restore_ckpt: "october_checkpoints/GroupwiseFull/GroupwiseFull_398.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8

Eval_config_8_GroupwisePhoto:
    <<: *eval_defaults
    name: "GroupwisePhoto"
    restore_ckpt: "october_checkpoints/GroupwisePhoto/GroupwisePhoto_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8

Eval_config_8_GroupwisePhotoSpa:
    <<: *eval_defaults
    name: "GroupwisePhotoSpa"
    restore_ckpt: "october_checkpoints/GroupwisePhotoSpa/GroupwisePhotoSpa_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8

Eval_config_8_GroupwisePhotoTemp:
    <<: *eval_defaults
    name: "GroupwisePhotoTemp"
    restore_ckpt: "october_checkpoints/GroupwisePhotoTemp/GroupwisePhotoTemp_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8
    
Eval_config_8_GroupwiseFull_198:
    <<: *eval_defaults
    name: "GroupwiseFull200"
    restore_ckpt: "october_checkpoints/GroupwiseFull200/GroupwiseFull200_198.pth"
    add_normalisation: False
    model: 'group'
    max_seq_len: 8
    
Eval_config_8_PairwiseFull:
    <<: *eval_defaults
    name: "PairwiseFull"
    restore_ckpt: "october_checkpoints/PairwiseFull/PairwiseFull_398.pth"
    add_normalisation: False
    model: 'pair'
    max_seq_len: 8
