wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1659710987.367125
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 2
      - 23
      4: 3.10.4
      5: 0.13.0
      8:
      - 1
      - 5
